### ISSUE TITLE
[Mod Support] Blockus, Extended Block Shape, BetterNether, BetterEnd

### ISSUE THREAD

**Issue by ardissaps** [blay09/KleethoMod#53]
Would you please support these mods? 

1. https://www.curseforge.com/minecraft/mc-mods/refabricated-slabs (Double Different Slab :https://imgur.com/a/yVwO3qw)
2. https://www.curseforge.com/minecraft/mc-mods/blockus
3. https://www.curseforge.com/minecraft/mc-mods/extended-block-shapes
4. https://www.curseforge.com/minecraft/mc-mods/betternether
5. https://www.curseforge.com/minecraft/mc-mods/betterend

Thank you very much. :)

**Comment by CebbyS** [comment]
Hi, I am the developer of Refabricated Slabs mod and I have a feature request so that the Refabricated Slabs mod could be compatible with the KleeSlabs mod.

Refabricated slabs mod is basically double slab block mod that can have mixed slabs - oak/cobblestone for example. The slabs are not stored in the block state. But as additional data to the chunk. And to make the SlabConverter interface compatible to convert the double slab block into respective slabs I need to have access to BlockPos and Level data, which comes from BreakBlockEvent.

I would suggest adding the following changes to the KleeSlabs mod, to make it more flexible.
1. Adding to the **SlabConverter** interface method **getSingleSlab** third parameter **BreakBlockEvent**, as it has all the necessary information and I will do the rest of the compatibility implementation in my mod.
> ```java
> BlockState getSingleSlab(BlockState state, SlabType slabType)
> ```
> ```java
> BlockState getSingleSlab(BlockState state, SlabType slabType, BreakBlockEvent event)
> ```
2. With this change **BlockBreakHandler** needs to be changed in 3 places by passing the event object to the converter.
> https://github.com/ModdingForBlockheads/KleeSlabs/blob/cea13277b01b9fdf1c091a6338104e01a2eb1664/shared/src/main/java/net/blay09/mods/kleeslabs/BlockBreakHandler.java#L44
>  https://github.com/ModdingForBlockheads/KleeSlabs/blob/cea13277b01b9fdf1c091a6338104e01a2eb1664/shared/src/main/java/net/blay09/mods/kleeslabs/BlockBreakHandler.java#L62
>  https://github.com/ModdingForBlockheads/KleeSlabs/blob/cea13277b01b9fdf1c091a6338104e01a2eb1664/shared/src/main/java/net/blay09/mods/kleeslabs/BlockBreakHandler.java#L64
3. And the implementations of SlabConverters must be changed
> https://github.com/ModdingForBlockheads/KleeSlabs/tree/cea13277b01b9fdf1c091a6338104e01a2eb1664/shared/src/main/java/net/blay09/mods/kleeslabs/converter
4. And if there are implementations of custom SlabConverters in other mods, that would be a change for them too. 

Thanks for the understanding and kind regards!

**Comment by CebbyS** [comment]
Hi!
Is there any chance that this is going to be a feature for near future versions in 1.18 and 1.19?
Kind regards!
